// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM5UkWLlQK4hjom4aKGey9SY9Z2qwpgR0',
    appId: '1:228649498780:web:40ea884c097d352053d559',
    messagingSenderId: '228649498780',
    projectId: 'jewels-81fe3',
    authDomain: 'jewels-81fe3.firebaseapp.com',
    storageBucket: 'jewels-81fe3.firebasestorage.app',
    measurementId: 'G-MEX52BZ207',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeTt1KVN-fOvLnqSLoUlBbKk-KKWE6U5k',
    appId: '1:228649498780:android:8b4979b2948baf0f53d559',
    messagingSenderId: '228649498780',
    projectId: 'jewels-81fe3',
    storageBucket: 'jewels-81fe3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvfhTNWZbC7YKULbAfhWzWoe4WS921JUU',
    appId: '1:228649498780:ios:3850838132d5e83653d559',
    messagingSenderId: '228649498780',
    projectId: 'jewels-81fe3',
    storageBucket: 'jewels-81fe3.firebasestorage.app',
    iosBundleId: 'com.example.jewels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvfhTNWZbC7YKULbAfhWzWoe4WS921JUU',
    appId: '1:228649498780:ios:3850838132d5e83653d559',
    messagingSenderId: '228649498780',
    projectId: 'jewels-81fe3',
    storageBucket: 'jewels-81fe3.firebasestorage.app',
    iosBundleId: 'com.example.jewels',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM5UkWLlQK4hjom4aKGey9SY9Z2qwpgR0',
    appId: '1:228649498780:web:52c8f09bd486feca53d559',
    messagingSenderId: '228649498780',
    projectId: 'jewels-81fe3',
    authDomain: 'jewels-81fe3.firebaseapp.com',
    storageBucket: 'jewels-81fe3.firebasestorage.app',
    measurementId: 'G-XEQXZJB8ZD',
  );
}
